name: Sauce Labs Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      LOGIN_GITHUB_PASSWORD: ${{ secrets.LOGIN_GITHUB_PASSWORD }}
      LOGIN_GITHUB_USERNAME: ${{ secrets.LOGIN_GITHUB_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Start Sauce Labs job
        run: |
          npm test
      
      # send telegram message when done
      # with a curl request
      - name: Send notification
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=Job%20completed%20on%20${{ github.repository }}%20branch%20${{ github.ref }}"


